import {
  FaRobot,
  FaBook,
  FaSitemap,
  FaClipboardCheck,
  FaChartLine,
  FaTrophy,
  FaArrowRight,
} from "react-icons/fa";

const featureData = [
  {
    number: "01",
    type: "mentor",
    badge: "NEW",
    title: "AI Mentor Replay",
    description:
      "Every learning session is automatically converted into notes, summaries, quizzes, mind maps and personalized action plans.",
    color: "from-violet-500 to-blue-500",
    icon: <FaRobot />,
  },

  {
    number: "02",
    type: "flashcard",
    badge: "AI",
    title: "AI Flashcards",
    description:
      "Instantly generate smart flashcards from your learning sessions for faster revision and better memory retention.",
    color: "from-pink-500 to-purple-500",
    icon: <FaBook />,
  },

  {
    number: "03",
    type: "mindmap",
    badge: "NEW",
    title: "AI Mind Maps",
    description:
      "Understand complex concepts visually with automatically generated AI mind maps.",
    color: "from-green-400 to-emerald-500",
    icon: <FaSitemap />,
  },

  {
    number: "04",
    type: "quiz",
    badge: "SMART",
    title: "AI Quiz Generator",
    description:
      "Practice immediately after every lesson with personalized quizzes generated by AI.",
    color: "from-orange-400 to-red-400",
    icon: <FaClipboardCheck />,
  },

  {
    number: "05",
    type: "timeline",
    badge: "PRO",
    title: "Growth Timeline",
    description:
      "Track your entire learning journey with a GitHub-style contribution graph and detailed progress analytics.",
    color: "from-cyan-400 to-blue-500",
    icon: <FaChartLine />,
  },

  {
    number: "06",
    type: "quest",
    badge: "XP",
    title: "Skill Quest",
    description:
      "Complete daily learning missions, earn XP, unlock achievements and level up your SkillMate profile.",
    color: "from-yellow-400 to-orange-500",
    icon: <FaTrophy />,
  },
];

export default featureData;